var NAVTREEINDEX0 =
{
"_troubleshooting.html":[4],
"cubemx.html":[1],
"cubemx_using.html":[2],
"cubemx_using.html#cubemx_clock_config":[2,1],
"cubemx_using.html#cubemx_proj":[2,0],
"cubemx_using.html#cubemx_proj_gen":[2,2],
"cubemx_using.html#cubemx_proj_overview":[2,3],
"cubemx_using.html#cubemx_proj_rtx5":[2,4],
"index.html":[],
"index.html":[0],
"pages.html":[],
"stm32_dfp.html":[3],
"stm32l0_i2c.html":[3,5],
"stm32l0_spi.html":[3,4],
"stm32l0_uart.html":[3,0],
"stm32l0_usart.html":[3,1],
"stm32l0_usart_irda.html":[3,3],
"stm32l0_usart_smart.html":[3,2],
"stm32l0_usbd.html":[3,6]
};
