#!/bin/bash
cd -- "$(dirname "$0")"
make -C libopencm3 TARGETS=stm32/l0
make clean -C coolease P=hub
make -C coolease P=hub
./util/upload/stm32flash/stm32flash -e 128 -w build/hub.bin -v \
-R -i -dtr,rts,-rts:dtr,rts,-rts /dev/cu.usbserial-A50285BI