set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_C_LINK_EXECUTABLE "<CMAKE_C_COMPILER> <FLAGS> <CMAKE_C_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> -Wl,--start-group <LINK_LIBRARIES> -lc -lm -Wl,--end-group -Wl,-Map=<TARGET>.map")
set(CMAKE_C_STANDARD 11)

# clear cmake default debug flags as we add them later
set(CMAKE_C_FLAGS_DEBUG "-O0 -g3 -DDEBUG" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS_RELEASE "-Os -g0 -DNDEBUG" CACHE STRING "" FORCE)

# turn off cmake auto setting -std as we add later
set(CMAKE_C_EXTENSIONS OFF)

set(CMAKE_C_COMPILER_ID GNU)

if(DEFINED ENV{ARM_TOOLCHAIN_PATH})
  set(ARM_TOOLCHAIN_PATH $ENV{ARM_TOOLCHAIN_PATH})
endif()

if(NOT DEFINED ARM_TOOLCHAIN_PATH)
  message(FATAL_ERROR "Must set ARM_TOOLCHAIN_PATH")
endif()

message(STATUS "ARM_TOOLCHAIN_PATH is set to: ${ARM_TOOLCHAIN_PATH}")


set(TOOLCHAIN_PREFIX ${ARM_TOOLCHAIN_PATH}/arm-none-eabi-)

set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})
set(CMAKE_LINKER ${TOOLCHAIN_PREFIX}g++)
set(CMAKE_OBJCOPY ${TOOLCHAIN_PREFIX}objcopy)
set(CMAKE_OBJDUMP ${TOOLCHAIN_PREFIX}objdump)
set(CMAKE_SIZE ${TOOLCHAIN_PREFIX}size)

set(CMAKE_EXECUTABLE_SUFFIX_C ".elf")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
