PROJECT 		= Hub

# TODO - you will need to edit these two lines!
DEVICE 		= 	stm32l052c8t6

# You shouldn't have to edit anything below here.
# INCLUDES 	+= 	-I../coolease/include

include Makefile.inc
