name: Ceedling Tests

on:
  push:
    branches-ignore: [production, develop]
  pull_request:
    branches: [production, develop]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'

    - name: Install Ceedling
      run: gem install ceedling

    - name: Run Ceedling tests
      run: ceedling test:printf
